### ISSUE TITLE
Incompatible with play 2.3.0-RC1

### ISSUE THREAD

**Issue by astorath** [webjars/webjars-play#40]
After upgrade to play 2.3.0-RC1, the following error occurred:

``` java
! Internal server error, for (GET) [/webjars/jquery/2.1.1/jquery.js] ->

java.lang.NoSuchMethodError: controllers.AssetsBuilder.at(Ljava/lang/String;Ljava/lang/String;)Lplay/api/mvc/Action;
        at controllers.WebJarAssets.at(WebJarAssets.scala:36) ~[webjars-play_2.10-2.3-M1.jar:2.3-M1]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:110) ~[na:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:110) ~[na:na]
        at play.core.Router$HandlerInvokerFactory$$anon$13$$anon$14.call(Router.scala:217) ~[play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
        at play.core.Router$Routes$TaggingInvoker.call(Router.scala:464) ~[play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
[error] application - Error while rendering default error page
scala.MatchError: java.lang.NoSuchMethodError: controllers.AssetsBuilder.at(Ljava/lang/String;Ljava/lang/String;)Lplay/api/mvc/Action; (of class java.lang.NoSuchMethodError)
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:148) ~[play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:206) [play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
        at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:76) [play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:86) [play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:84) [play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
[error] application - Error while rendering default error page
scala.MatchError: java.lang.NoSuchMethodError: controllers.AssetsBuilder.at(Ljava/lang/String;Ljava/lang/String;)Lplay/api/mvc/Action; (of class java.lang.NoSuchMethodError)
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:148) ~[play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:206) [play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
        at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:76) [play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:86) [play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:84) [play_2.10-2.3.0-RC1.jar:2.3.0-RC1]
[error] application -
```

The problem is probably caused by this change: [https://github.com/playframework/playframework/commit/a1db6ff8658914d651f82d0c5dbe24b6e5f1e649].

![2014-05-10_13-07-35](https://cloud.githubusercontent.com/assets/6577390/2935680/9264f998-d822-11e3-8dc9-c0f8e6170395.png)

**Comment by knjendu** [comment]
Hi I'm having the same issue when using webjars-play 2.5.0

`Caused by: java.lang.NoSuchMethodError: controllers.AssetsBuilder.<init>(Lplay/api/http/HttpErrorHandler;)V
	at controllers.WebJarAssets.<init>(WebJarAssets.scala:19)
	at controllers.WebJarAssets$$FastClassByGuice$$db4380e1.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:405)
	at play.api.inject.RoutesProvider$$anonfun$2.apply(BuiltinModule.scala:108)
	at play.api.inject.RoutesProvider$$anonfun$2.apply(BuiltinModule.scala:108)
	at scala.Option.fold(Option.scala:158)
	at play.api.inject.RoutesProvider.get$lzycompute(BuiltinModule.scala:108)
	at play.api.inject.RoutesProvider.get(BuiltinModule.scala:104)
	at play.api.inject.RoutesProvider.get(BuiltinModule.scala:103)
`

**Comment by jamesward** [comment]
@knjendu What version of Play?
