### ISSUE TITLE
Incompatibility with play 2.4.0-M3 and routesGenerator := InjectedRoutesGenerator

### ISSUE THREAD

**Issue by davidillsley** [webjars/webjars-play#51]
When I try to use webjars with Play/Java and ```routesGenerator := InjectedRoutesGenerator``` as described in https://www.playframework.com/documentation/2.4.x/Migration24 I get:

```
[error] 1) Could not find a suitable constructor in controllers.WebJarAssets. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
[error]   at controllers.WebJarAssets.class(WebJarAssets.scala:18)
[error]   while locating controllers.WebJarAssets
[error]     for parameter 3 at Routes.<init>(routes_routing.scala:36)
[error]   while locating Routes
[error]   while locating play.api.test.FakeRouterProvider
[error]   while locating play.api.routing.Router
[error] 
[error] 1 error, took 0.044 sec
[error]     at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
[error]     at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
[error]     at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:314)
[error]     at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:309)
[error]     at play.api.Application$class.routes(Application.scala:103)
[error]     at play.api.test.FakeApplication.routes(Fakes.scala:201)
[error]     at play.api.Play$.start(Play.scala:89)
[error]     at play.api.Play.start(Play.scala)
[error]     at play.test.Helpers.start(Helpers.java:455)
[error]     at play.test.Helpers.running(Helpers.java:471)

```

**Comment by jamesward** [comment]
`2.4.0-M3-1` will be released shortly with the fix for this.

**Comment by asheshambasta** [comment]
This isn't fixed.

**Comment by jamesward** [comment]
What version of `webjars-play` are you using?  The [sample project](https://github.com/webjars/sample-play2) seems to be working fine.  What is the problem you are having?

**Comment by vikash002** [comment]
I am getting same problem please provide me solution for this .

**Comment by jamesward** [comment]
@vikash002 Are you using the latest version of this library?  What version of Play?  Can you provide any error messages you are getting?

**Comment by vikash002** [comment]
No my issue is now solved thanks
