### ISSUE TITLE
Dependency mismatch with play 2.6.3

### ISSUE THREAD

**Issue by alexflav23** [webjars/webjars-play#78]
I have a small problem after upgrading to play 2.6.3 and using webjars 2.6.1, have not changed any of the code outside of the versions.

```scala
3) Error injecting constructor, java.lang.NoSuchMethodError: controllers.AssetsBuilder.<init>(Lplay/api/http/HttpErrorHandler;)V
[info]   at controllers.WebJarAssets.<init>(WebJarAssets.scala:19)
[info]   at controllers.WebJarAssets.class(WebJarAssets.scala:19)
[info]   while locating controllers.WebJarAssets
```

Have you seen this before as it looks like a binary incompatibility at library level?

**Comment by jamesward** [comment]
This might be due to some API changes: https://github.com/webjars/webjars-play/compare/v2.6.0...v2.6.1

Can you check the updated WebJars Play docs: http://www.webjars.org/documentation#play2

Let me know if that helps.

BTW: Our versioning follows Play versioning to indicate compat with Play.  But it doesn't follow semver at the library level.  This is a pain - sorry.

**Comment by alexflav23** [comment]
@jamesward It is because the `WebJarAssets` implicitly included in scope somehow was `controller.WebjarAssets`. I still don't and cannot understand where that came from, because it doesn't seem included in the code. That variant was not passing through the `errorHandler` and something else to `controllers.AssetBuilder`, so it ended up being a runtime incompatible class change error basically.

I worked it out in the end, but I really don't know if that `controllers.WebJarAssets` is somehow a problem on our end or if it could be something affecting other people, I suppose you have better insight there.

**Comment by jamesward** [comment]
Very odd.  But glad we have info here in case anyone else runs into this.
